---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

require:
  - rubocop-capybara
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/dummy/**/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/RaiseArgs:
  EnforcedStyle: compact

Style/EmptyMethod:
  Exclude:
    - spec/**/*

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 130
  Exclude:
    - spec/**/*

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

##########
# NAMING #
##########

Naming/BlockForwarding:
  Enabled: false

#########
# RSPEC #
#########

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ChangeByZero:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not
