AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - gemfiles/*
    - test/**/*

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Naming/PredicateName:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
