language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
gemfile:
  - gemfiles/rails_4.2.8.gemfile
  - gemfiles/rails_5.0.2.gemfile
  - gemfiles/rails_5.1.0.gemfile
script:
  - cd test/dummy/
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
