language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.2.gemfile
before_install:
  - gem update --system
  - gem install bundler --no-document
after_success:
  - bundle exec codeclimate-test-reporter
script:
  - cd test/dummy/
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
