dist: trusty
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
gemfile:
  - gemfiles/rails_4.2.10.gemfile
  - gemfiles/rails_5.0.6.gemfile
  - gemfiles/rails_5.1.4.gemfile
  - gemfiles/rails_5.2.0.beta2.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
script:
  - cd test/dummy/
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
