language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.3
  - 2.2.6
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_4.gemfile
script:
  - cd test/dummy/
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
